/*
 * This file is generated by jOOQ.
 */
package com.tokumura.librarian.infrastructure.database.jooq.keys


import com.tokumura.librarian.infrastructure.database.jooq.tables.Author
import com.tokumura.librarian.infrastructure.database.jooq.tables.Book
import com.tokumura.librarian.infrastructure.database.jooq.tables.FlywaySchemaHistory
import com.tokumura.librarian.infrastructure.database.jooq.tables.records.AuthorRecord
import com.tokumura.librarian.infrastructure.database.jooq.tables.records.BookRecord
import com.tokumura.librarian.infrastructure.database.jooq.tables.records.FlywaySchemaHistoryRecord

import org.jooq.ForeignKey
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val AUTHOR_PKEY: UniqueKey<AuthorRecord> = Internal.createUniqueKey(Author.AUTHOR, DSL.name("author_pkey"), arrayOf(Author.AUTHOR.ID), true)
val BOOK_PKEY: UniqueKey<BookRecord> = Internal.createUniqueKey(Book.BOOK, DSL.name("book_pkey"), arrayOf(Book.BOOK.ID), true)
val FLYWAY_SCHEMA_HISTORY_PK: UniqueKey<FlywaySchemaHistoryRecord> = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), arrayOf(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK), true)

// -------------------------------------------------------------------------
// FOREIGN KEY definitions
// -------------------------------------------------------------------------

val BOOK__BOOK_FK1: ForeignKey<BookRecord, AuthorRecord> = Internal.createForeignKey(Book.BOOK, DSL.name("book_fk1"), arrayOf(Book.BOOK.AUTHOR_ID), com.tokumura.librarian.infrastructure.database.jooq.keys.AUTHOR_PKEY, arrayOf(Author.AUTHOR.ID), true)
