/*
 * This file is generated by jOOQ.
 */
package com.tokumura.librarian.infrastructure.database.jooq.tables.references


import com.tokumura.librarian.infrastructure.database.jooq.tables.Author
import com.tokumura.librarian.infrastructure.database.jooq.tables.Book
import com.tokumura.librarian.infrastructure.database.jooq.tables.FlywaySchemaHistory



/**
 * The table <code>public.author</code>.
 */
val AUTHOR: Author = Author.AUTHOR

/**
 * The table <code>public.book</code>.
 */
val BOOK: Book = Book.BOOK

/**
 * The table <code>public.flyway_schema_history</code>.
 */
val FLYWAY_SCHEMA_HISTORY: FlywaySchemaHistory = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY
