/*
 * This file is generated by jOOQ.
 */
package com.tokumura.librarian.infrastructure.database.jooq.indexes


import com.tokumura.librarian.infrastructure.database.jooq.tables.Book
import com.tokumura.librarian.infrastructure.database.jooq.tables.FlywaySchemaHistory

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val BOOK_IDX1: Index = Internal.createIndex(DSL.name("book_idx1"), Book.BOOK, arrayOf(Book.BOOK.AUTHOR_ID), false)
val FLYWAY_SCHEMA_HISTORY_S_IDX: Index = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, arrayOf(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS), false)
