/*
 * This file is generated by jOOQ.
 */
package com.tokumura.librarian.infrastructure.database.jooq.tables.records


import com.tokumura.librarian.infrastructure.database.jooq.tables.Author

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class AuthorRecord private constructor() : UpdatableRecordImpl<AuthorRecord>(Author.AUTHOR) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var name: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    open var url: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised AuthorRecord
     */
    constructor(id: Int? = null, name: String, url: String? = null): this() {
        this.id = id
        this.name = name
        this.url = url
        resetChangedOnNotNull()
    }
}
